// spec: https://webidl.spec.whatwg.org/

// notes:
// - by default, objects are taken as pointers
//   use [Value] to indicate the object itself
// - int is a long (32 bits)
// - use [NoDelete] for abstract classes as they do not have a destructor

//////// Math ////////

[Prefix="ephys::"]
interface Vec2 {
  attribute float x;
  attribute float y;

  void Vec2();
  void Vec2([Const] float x, [Const] float y);
  void Vec2([Const, Ref] Vec2 x);

  void set([Const] float x, [Const] float y);

  float norm();
  float norm2();
  [Ref] Vec2 normalize();

  [Operator="+=", Ref] Vec2 add([Const, Ref] Vec2 v);
  [Operator="-=", Ref] Vec2 sub([Const, Ref] Vec2 v);
  [Operator="*=", Ref] Vec2 mult(float k);
};

[Prefix="ephys::"]
interface Mat2 {
  attribute float[] data;

  void Mat2();
  void Mat2(float d11, float d12,
            float d21, float d22);
  void Mat2([Const, Ref] Mat2 m);

  [Value] static Mat2 zero();
  [Value] static Mat2 identity();

  float at(unsigned long m, unsigned long n);
  void set(unsigned long m, unsigned long n, float val);

  [Operator="+=", Ref] Mat2 add([Const, Ref] Mat2 m);
  [Operator="-=", Ref] Mat2 sub([Const, Ref] Mat2 m);
  [Operator="*=", Ref] Mat2 mult([Const, Ref] Mat2 m);

  float determinant();

  [Value] Mat2 inverse();
  [Ref] Mat2 invert();

  [Value] Mat2 transpose();
};

[Prefix="ephys::"]
interface Mat3 {
  void Mat3();
  void Mat3(float d11, float d12, float d13,
            float d21, float d22, float d23);
  void Mat3([Const, Ref] Mat3 m);

  [Value] static Mat3 identity();

  float at(unsigned long m, unsigned long n);
  void set(unsigned long m, unsigned long n, float val);

  float determinant();

  [Value] Mat3 inverse();
  [Ref] Mat3 invert();
};

//////// Particles ////////

[Prefix="ephys::"]
interface Particle {
  void Particle(optional float mass, optional float damping);

  [Value] Vec2 getPos();
  [Value] Vec2 getVel();
  [Value] Vec2 getAcc();
  float getMass();
  float getInvMass();
  float getDamping();

  void setPos([Const, Ref] Vec2 pos);
  void setVel([Const, Ref] Vec2 vel);
  void setAcc([Const, Ref] Vec2 acc);
  void setMass(float mass);
  void setInvMass(float mass);
  void setDamping(float damping);

  void addForce([Const, Ref] Vec2 force);
  void addImpulse([Const, Ref] Vec2 impulse);

  void clearForceAccum();

  void setStatic();
  boolean isStatic();

  void step(float dt);
};

//////// Particle Force Generators ////////

[Prefix="ephys::", NoDelete]
interface ParticleForceGenerator {
  void updateForce([Ref] Particle particle, float dt);
};

[Prefix="ephys::"]
interface ParticleForceRegistry {
  void ParticleForceRegistry();

  void add([Ref] Particle particle, [Ref] ParticleForceGenerator fgen);
  void remove([Ref] Particle particle, [Ref] ParticleForceGenerator fgen);
  void clear();

  void step(float dt);
};

[Prefix="ephys::"]
interface ParticleGravity : ParticleForceGenerator {
  void ParticleGravity([Const, Ref] Vec2 gravity);
  void updateForce([Ref] Particle particle, float dt);
};
[Prefix="ephys::"]
interface ParticleDrag : ParticleForceGenerator {
  void ParticleDrag(float k1, float k2);
  void updateForce([Ref] Particle particle, float dt);
};
[Prefix="ephys::"]
interface ParticleSpring : ParticleForceGenerator {
  attribute float k;
  attribute float length;
  void ParticleSpring([Ref] Particle end, float k, float length);
  void setEnd([Const, Ref] Particle particle);
  [Value] Particle getEnd();
  void updateForce([Ref] Particle particle, float dt);
};

//////// Particle Contacts ////////
[Prefix="ephys::"]
interface ParticleContact {
  attribute Particle[] particles;
  attribute float restitution;
  [Value] attribute Vec2 contactNormal;
  attribute float penetration;

  float separatingVelocity();
};

// placeholder for std::list<ephys::ParticleContact>
[NoDelete]
interface PContactList {};

[Prefix="ephys::"]
interface ParticleContactSolver {
  void ParticleContactSolver(unsigned long maxIterations);

  unsigned long getIterations();
  void setIterations(unsigned long iterations);

  void solveContacts([Ref] PContactList contacts, float dt);
};

[Prefix="ephys::", NoDelete]
interface ParticleContactGenerator {
  [Ref] PContactList generateContacts();
};

//////// Particle Links ////////
[Prefix="ephys::", NoDelete]
interface ParticleLink : ParticleContactGenerator {
  void setParticle(unsigned long index, [Ref] Particle particle);
  [Ref] Particle getParticle(unsigned long index);

  [Ref] PContactList generateContacts();
};

[Prefix="ephys::"]
interface ParticleCable : ParticleLink {
  attribute float length;
  attribute float restitution;

  void ParticleCable(float length, float restitution);
  
  void setParticle(unsigned long index, [Ref] Particle particle);
  [Ref] Particle getParticle(unsigned long index);
  
  [Ref] PContactList generateContacts();
};

[Prefix="ephys::"]
interface ParticleRod : ParticleLink {
  attribute float length;

  void ParticleRod(float length);
  
  void setParticle(unsigned long index, [Ref] Particle particle);
  [Ref] Particle getParticle(unsigned long index);
  
  [Ref] PContactList generateContacts();
};

//////// Particle World ////////
[Prefix="ephys::"]
interface ParticleWorld {
  void ParticleWorld(optional unsigned long iterations);

  [Ref] ParticleForceRegistry getPFReg();

  void addParticle([Ref] Particle particle);
  void removeParticle([Ref] Particle particle);

  void addPContactGenerator([Ref] ParticleContactGenerator pcg);
  void removePContactGenerator([Ref] ParticleContactGenerator pcg);
  
  [Ref] PContactList generateContacts();

  void step(float dt);
};
