name: "ephys: Release Build"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone emsdk
        run: |
          cd ${{github.workspace}}
          git clone https://github.com/emscripten-core/emsdk.git
      - name: Install emsdk
        run: |
          ${{github.workspace}}/emsdk/emsdk install latest
      - name: Activate emsdk
        run: |
          ${{github.workspace}}/emsdk/emsdk activate latest
          source ${{github.workspace}}/emsdk/emsdk_env.sh
          echo "EMSDK=$EMSDK" >> $GITHUB_ENV
      - name: Configure CMake
        run: |
          cd ${{github.workspace}}
          mkdir build
          cd build
          ${{github.workspace}}/emsdk/upstream/emscripten/emcmake cmake .. -D CMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          echo emsdk: $EMSDK
          echo github_env: $GITHUB_ENV
          cmake --build ${{github.workspace}}/build -t clean
          cmake --build ${{github.workspace}}/build -t ephys
