name: Release Build
on:
  push:
  workflow_dispatch:

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone emsdk
        run: |
          cd ${{github.workspace}}
          git clone https://github.com/emscripten-core/emsdk.git
      - name: Install emsdk
        run: |
          ${{github.workspace}}/emsdk/emsdk install latest
      - name: Activate emsdk
        run: |
          ${{github.workspace}}/emsdk/emsdk activate latest
          source ${{github.workspace}}/emsdk/emsdk_env.sh
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo "EMSDK=$EMSDK" >> $GITHUB_ENV
      - name: Configure CMake
        run: |
          cd ${{github.workspace}}
          mkdir build
          cd build
          emcmake cmake .. -D CMAKE_BUILD_TYPE=Debug
      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build -t clean
          cmake --build ${{github.workspace}}/build -t ephys
          git status
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Create release build
          file_pattern: demos/**
